# Generated by Django 6.0.1 on 2026-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
    ]
