# Generated by Django 6.0.1 on 2026-06-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_pedido_estado_pedido_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
