# Generated by Django 6.0.1 on 2026-06-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Estimado')),
                ('etapa', models.CharField(choices=[('prospeccion', 'Prospección'), ('propuesta', 'Propuesta'), ('negociacion', 'Negociación'), ('ganada', 'Cerrada Ganada'), ('perdida', 'Cerrada Perdida')], default='prospeccion', max_length=20)),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Oportunidades',
            },
        ),
    ]
