# Generated by Django 6.0.1 on 2026-06-10 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='dias_abierta',
            field=models.IntegerField(default=0, verbose_name='Días Abierta'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre'),
        ),
    ]
